Add unit tests to the library
mathildebrosseau/transition-python-lib pull request #28
Opened 2024-03-30 18:42 UTC by manelkdm

2024-04-02 14:33 UTC, mathildebrosseau requested changes
Je pense que y'a plusieurs trucs dont on va pouvoir se reparler tantôt en personne, mais globalement je pense que y'a beaucoup de validations qu'on peut enlever parce ça duplique les tests de l'API et/ou ça teste des trucs qui ne dépendent pas de nos méthodes.

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +    def setUp(self):
c'est du gros nitpicking mais setUp devrait être en snake case hahaha

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +        Transition.TOKEN = None
pour build_headers, peut-être qu'il faudrait aussi tester que si Transition.TOKEN est valide mais le paramètre est None ca marche quand même ? En fait on devrait aussi tester sans spécifier le paramètre du tout vu qu'il a une valeur par défaut ?

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            res = Transition.request_token(self.test_username, self.test_password, self.test_url)
ici je pense que c'est pas nécessaire de faire la requête 2x

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            res = Transition.request_token(self.test_username, self.test_password, self.test_url)
du moins faudrait renommer les variables pcq response vs res est pas clair (en s'en parlera tantôt)

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertRaises(requests.exceptions.HTTPError, response.raise_for_status)
ici ça devrait pas être request_token qu'on appelle au lieu de raise_for_status? Sinon ça revient à tester requests.post au lieu de notre méthode

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertEqual(response.json(), {"key" : "value"})
je suis pas convaincue par ce test, j'ai l'impression que ça revient à dupliquer les tests de l'API plutôt que de tester notre librairie. Genre dans les tests de la librairie, le but est de tester qu'on appelle resquest avec les bons paramètres, pas de tester que l'API retourne la bonne chose je crois, parce que ça c'est déjà fait dans les tests de l'API lui-même

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertRaises(requests.exceptions.HTTPError, Transition.get_paths)
ahhh ça j'aime bien!!

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertEqual(response.status_code, 400)
ici je pense que ça sert à rien de tester le code de retour si on a nous-même choisi le code de retour en configurant le mock

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertEqual(response.status_code, 400)
(valable pour tous les tests en fait)

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            Transition.request_accessibility_map(0, 0, "scenario-id", 'Departure', departure_time, 1, 1, 1, 'place', 1, 1, 1, 1, 1, 1, True)
ça pourrait être utile d'expliciter les noms de paramètres pour que ce soit plus parlant (genre maxTravelTime=1 au lieu de juste 1)

2024-04-02 14:33 UTC, mathildebrosseau commented on tests/test_transition.py
> +            self.assertEqual(m.last_request.headers['Authorization'], f"Bearer {self.test_token}")
on pourrait pt juste tester que build_headers a été appelé? vu qu'on l'a déjà testé

2024-04-02 14:44 UTC, manelkdm commented on tests/test_transition.py
> +            self.assertEqual(response.json(), {"key" : "value"})
fair enough ! du coup juste des called oce / called with ?

2024-04-08 13:58 UTC, mathildebrosseau approved these changes

2024-04-08 13:59 UTC, merged