Finished documentation
mathildebrosseau/transition-python-lib pull request #29
Opened 2024-03-31 03:12 UTC by manelkdm

Finished the library documentation and changed some methods to private.

2024-04-02 15:00 UTC, mathildebrosseau requested changes

2024-04-02 15:00 UTC, mathildebrosseau commented on transition_lib/transition_api_lib.py
> +    def _build_body(username, password):
c'est pas 2 _ qu'il faut mettre pour que la méthode soit privée en python?

2024-04-02 15:01 UTC, mathildebrosseau commented on README.md
> +&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;ID of the used scenario as loaded in Transition application.\
on pourrait pt en profiter dans cette PR pour le fix ?

2024-04-02 15:06 UTC, manelkdm commented on README.md
> +    # The login information can be saved in a file to not have them displayed in the code
j'avais pas envie de faire un example de fichier parce que réalistiquement ça peut être n'importe quel type (txt, ini, env..) so j'avais pas envie de donner l'impression que faut utiliser l'un ou l'autre, mais on peut en choisir un comme example

2024-04-04 16:22 UTC, mathildebrosseau commented on transition_lib/transition_api_lib.py
>          url = Transition.API_URL if url is None else url
ici faudrait appeler set_parameters

2024-04-04 21:44 UTC, mathildebrosseau approved these changes

2024-04-04 21:53 UTC, merged